baseURL = "https://skhro87.github.io/blog/"
languageCode = "en-us"
title = "seb's blob"
theme = "m10c"

[params]
  author = "seb"
  description="code and more"
  [[params.social]]
    name = "github"
    url = "https://github.com/skhro87"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"